---
title: "Quantify changes in species density across species climatic niches adjusting for stand development"
output: github_document
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
pre {
  font-size: 10px
}
</style>

```{r setup, include = F}
knitr::opts_chunk$set(eval = T, echo = TRUE, message = F, warning = F, out.width = "100%")

library(here)
library(tidyverse)
library(patchwork)
library(ggdist)
library(testthat)
library(fs)
library(gt)
library(magick)

```

```{r read}

read_data <- function(data_dir) {
  fs::dir_ls(data_dir, regexp = "\\.rds$") |>
    purrr::map(read_rds)
}

all_files <- read_data(data_dir = here("01_data", "species_predictions"))

all_files_dir <- dir_ls(here("01_data", "species_predictions"), regexp = "\\.rds$")

all_files_dir_names <- map(all_files_dir, ~str_extract(.x, "[^/]*$")) |> 
  map(~str_replace(.x, "_", " ")) |> 
  map(~str_extract(.x,  "[^_]+")) |>
  unname()

names(all_files) <- all_files_dir_names

eu_sp <- c(
  "Pinus halepensis",  
  "Quercus ilex",      
  "Quercus faginea",   
  "Pinus nigra",       
  "Pinus sylvestris",  
  "Fagus sylvatica",   
  "Quercus pyrenaica", 
  "Populus tremula",   
  "Betula pendula",    
  "Fraxinus excelsior",
  "Pinus pinaster",    
  "Pinus pinea",       
  "Quercus robur",     
  "Alnus glutinosa",   
  "Larix decidua",     
  "Picea abies",       
  "Betula pubescens",  
  "Carpinus betulus"
)

all_files_tb <- map2_df(all_files, names(all_files), \(x, y) mutate(x, species.cor = y))

map(all_files_tb, \(x) sum(is.na(x)))

predictions_all_changes <- all_files_tb

```

```{r all_sp}

names(predictions_all_changes)

predictions_all_changes_y_ha <- predictions_all_changes |> 
  mutate(
    predFE_observed_cold_wet_y_ha = (predFE_observed_cold_wet - n.plot0) / census.interval / plot.area,
    predFE_observed_core_y_ha = (predFE_observed_core - n.plot0) / census.interval / plot.area,
    predFE_observed_warm_arid_y_ha = (predFE_observed_warm_arid - n.plot0) / census.interval / plot.area,
    predFE_low_cold_wet_y_ha = (predFE_low_cold_wet - n.plot0) / census.interval / plot.area,
    predFE_low_core_y_ha = (predFE_low_core - n.plot0) / census.interval / plot.area,
    predFE_low_warm_arid_y_ha = (predFE_low_warm_arid - n.plot0) / census.interval / plot.area,
    predFE_high_cold_wet_y_ha = (predFE_high_cold_wet - n.plot0) / census.interval / plot.area,
    predFE_high_core_y_ha = (predFE_high_core - n.plot0) / census.interval / plot.area,
    predFE_high_warm_arid_y_ha = (predFE_high_warm_arid - n.plot0) / census.interval / plot.area
  ) |> 
  select(!c(
    predFE_observed_cold_wet,
    predFE_observed_core,
    predFE_observed_warm_arid,
    predFE_low_cold_wet,
    predFE_low_core,
    predFE_low_warm_arid,
    predFE_high_cold_wet,
    predFE_high_core,
    predFE_high_warm_arid
  ))

pred_all_changes_l <- predictions_all_changes_y_ha |>
  pivot_longer(
    cols = c(
      predFE_observed_cold_wet_y_ha,
      predFE_observed_warm_arid_y_ha, predFE_observed_core_y_ha,
      predFE_low_cold_wet_y_ha,
      predFE_low_warm_arid_y_ha, predFE_low_core_y_ha,
      predFE_high_cold_wet_y_ha,
      predFE_high_warm_arid_y_ha, predFE_high_core_y_ha
      ),
    names_to = "name_predFE_fd",
    values_to = "val_predFE_fd"
    )

pred_changes_l_rel <- pred_all_changes_l |>
  mutate(
    name_predFE_fd = fct_relevel(
    name_predFE_fd, 
    "predFE_observed_cold_wet_y_ha",
    "predFE_observed_core_y_ha", "predFE_observed_warm_arid_y_ha",
    "predFE_low_cold_wet_y_ha",
    "predFE_low_core_y_ha", "predFE_low_warm_arid_y_ha",
    "predFE_high_cold_wet_y_ha", "predFE_high_core_y_ha",
    "predFE_high_warm_arid_y_ha"
    ),
    for_dev = case_when(
      (name_predFE_fd == "predFE_observed_cold_wet_y_ha" | 
        name_predFE_fd == "predFE_observed_core_y_ha" |
        name_predFE_fd == "predFE_observed_warm_arid_y_ha") ~ "Actual stand development",
      (name_predFE_fd == "predFE_low_cold_wet_y_ha" | 
        name_predFE_fd == "predFE_low_core_y_ha" |
        name_predFE_fd == "predFE_low_warm_arid_y_ha") ~ "Early stand development",
        T ~ "Late stand development"
    ),
    name_predFE_fd = recode_factor(
      name_predFE_fd,
      "predFE_observed_cold_wet_y_ha" = "Cold & wet",
      "predFE_observed_core_y_ha" = "Median climate",
      "predFE_observed_warm_arid_y_ha" = "Warm & arid",
      "predFE_low_cold_wet_y_ha" = "Cold & wet",
      "predFE_low_core_y_ha" = "Median climate",
      "predFE_low_warm_arid_y_ha" = "Warm & arid",
      "predFE_high_cold_wet_y_ha" = "Cold & wet",
      "predFE_high_core_y_ha" = "Median climate",
      "predFE_high_warm_arid_y_ha" = "Warm & arid"
      )
  )

pred_changes_l_rel_eu <- pred_changes_l_rel |> 
  filter(species.cor %in% eu_sp)

pred_changes_l_rel_us <- pred_changes_l_rel |> 
  filter(!species.cor %in% eu_sp)

gg_slab_sp_clim <- function(dat) {
  ggplot(dat, aes(y = fct_rev(species.cor), x = val_predFE_fd,
                  fill = factor(name_predFE_fd,
                                levels = rev(c("Cold & wet",
                                               "Median climate",
                                               "Warm & arid"))),
                  color = factor(name_predFE_fd,
                                 levels = rev(c("Cold & wet",
                                                "Median climate",
                                                "Warm & arid"))))
  ) +
    stat_pointinterval(
      point_interval = mean_qi, .width = .5,
      position = position_dodge(width = .7), alpha = .9,
      ) +
    facet_wrap(~factor(for_dev, levels = c("Actual stand development", "Early stand development", "Late stand development"))) +
    geom_vline(xintercept = 0, linetype = "dashed") +
    labs(x = "Annual change n. stems per hectare", y = "") +
    scale_fill_manual(values = rev(c("lightskyblue", "gray7", "firebrick3")),
                      name = "",
                      guide = guide_legend(reverse = T)) +
    scale_color_manual(values = rev(c("lightskyblue", "gray7", "firebrick3")),
                       name = "", 
                       guide = guide_legend(reverse = T)) +
    theme(
      legend.position = "top",
      plot.title = element_text(color = "black", size = 10),
      plot.subtitle = element_text(color = "black", size = 8),
      panel.grid.major = element_blank(),
      panel.background = element_blank(),
      axis.title.y = element_blank(),
      legend.key = element_blank(),
      legend.text = element_text(color = "black", size = 9),
      axis.title.x = element_text(color = "black", size = 9),
      axis.text.x = element_text(color = "black", size = 9),
      axis.text.y = element_text(color = "black", size = 9,
                                 face = "italic")
      )
}

fig3_intrasp_eu_clim <- gg_slab_sp_clim(pred_changes_l_rel_eu)

ggsave(
  plot = fig3_intrasp_eu_clim,
  here("03_results", "figures", "fig3", "fig3_intrasp_eu.png"),
  width = 8, height = 8,
  dpi = 600
)

length(unique(pred_changes_l_rel_us$species.cor)) / 3

sp_1_18 <- unique(pred_changes_l_rel_us$species.cor)[1:18]

sp_19_36 <- unique(pred_changes_l_rel_us$species.cor)[19:36]

sp_37_55 <- unique(pred_changes_l_rel_us$species.cor)[37:55]

pred_us_sp_1_18 <- pred_changes_l_rel_us |> 
  filter(species.cor %in% sp_1_18)

pred_us_sp_19_36 <- pred_changes_l_rel_us |> 
  filter(species.cor %in% sp_19_36)

pred_us_sp_37_55 <- pred_changes_l_rel_us |> 
  filter(species.cor %in% sp_37_55)

pred_us_all <- list(
  pred_us_sp_1_18,
  pred_us_sp_19_36,
  pred_us_sp_37_55
)

gg_pred_us_all <- map(pred_us_all, \(x) gg_slab_sp_clim(x))

v_pred_us_all <- c(
  "pred_us_sp_1_18.png",
  "pred_us_sp_19_36.png",
  "pred_us_sp_37_55.png"
)

walk2(gg_pred_us_all, v_pred_us_all, \(x, y) ggsave(
  plot = x,
  filename = here("03_results", "figures", "fig3", y),
  width = 8, height = 8,
  dpi = 600
  ))

```

```{r table}

predictions_all_changes_y_ha_sp <- predictions_all_changes_y_ha |> 
  group_by(species.cor) |> 
  summarise(
    predFE_observed_cold_wet_y_ha_mean = mean(predFE_observed_cold_wet_y_ha),
    predFE_observed_cold_wet_y_ha_se = 
      sd(predFE_observed_cold_wet_y_ha) / sqrt(n()),
    predFE_observed_warm_arid_y_ha_mean = mean(predFE_observed_warm_arid_y_ha),
    predFE_observed_warm_arid_y_ha_se = 
      sd(predFE_observed_warm_arid_y_ha) / sqrt(n()),
    predFE_low_cold_wet_y_ha_mean = mean(predFE_low_cold_wet_y_ha),
    predFE_low_cold_wet_y_ha_se = 
      sd(predFE_low_cold_wet_y_ha) / sqrt(n()),
    predFE_low_warm_arid_y_ha_mean = mean(predFE_low_warm_arid_y_ha),
    predFE_low_warm_arid_y_ha_se = 
      sd(predFE_low_warm_arid_y_ha) / sqrt(n()),
    predFE_high_cold_wet_y_ha_mean = mean(predFE_high_cold_wet_y_ha),
    predFE_high_cold_wet_y_ha_se = 
      sd(predFE_high_cold_wet_y_ha) / sqrt(n()),
    predFE_high_warm_arid_y_ha_mean = mean(predFE_high_warm_arid_y_ha),
    predFE_high_warm_arid_y_ha_se = 
      sd(predFE_high_warm_arid_y_ha) / sqrt(n())
  )

predictions_imp <- predictions_all_changes_y_ha_sp |> 
  group_by(species.cor) |> 
  summarise(
    # observed
    dif_observed_mean = predFE_observed_cold_wet_y_ha_mean - 
      predFE_observed_warm_arid_y_ha_mean,
    dif_observed_se = sqrt(predFE_observed_cold_wet_y_ha_se ^ 2 +
                             predFE_observed_warm_arid_y_ha_se ^ 2),
    dif_observed_se_2 = dif_observed_se * 1.96,
    dif_observed_mean_se_2_neg = dif_observed_mean - dif_observed_se_2,
    dif_observed_mean_se_2_pos = dif_observed_mean + dif_observed_se_2,
    dif_observed_signi = between(
      0, dif_observed_mean_se_2_neg, dif_observed_mean_se_2_pos
    ), 
    # low
    dif_low_mean = predFE_low_cold_wet_y_ha_mean - 
      predFE_low_warm_arid_y_ha_mean,
    dif_low_se = sqrt(predFE_low_cold_wet_y_ha_se ^ 2 +
                             predFE_low_warm_arid_y_ha_se ^ 2),
    dif_low_se_2 = dif_low_se * 1.96,
    dif_low_mean_se_2_neg = dif_low_mean - dif_low_se_2,
    dif_low_mean_se_2_pos = dif_low_mean + dif_low_se_2,
    dif_low_signi = between(
      0, dif_low_mean_se_2_neg, dif_low_mean_se_2_pos
    ), 
    # high
    dif_high_mean = predFE_high_cold_wet_y_ha_mean - 
      predFE_high_warm_arid_y_ha_mean,
    dif_high_se = sqrt(predFE_high_cold_wet_y_ha_se ^ 2 +
                             predFE_high_warm_arid_y_ha_se ^ 2),
    dif_high_se_2 = dif_high_se * 1.96,
    dif_high_mean_se_2_neg = dif_high_mean - dif_high_se_2,
    dif_high_mean_se_2_pos = dif_high_mean + dif_high_se_2,
    dif_high_signi = between(
      0, dif_high_mean_se_2_neg, dif_high_mean_se_2_pos
    )
  )

table(predictions_imp$dif_observed_signi)
table(predictions_imp$dif_low_signi)
table(predictions_imp$dif_high_signi)

sp_importance_signi <- predictions_imp |> 
  mutate(
    observed_climsen_signi = ifelse(
      dif_observed_signi == F, paste(round(dif_observed_mean, 2), "*"), round(dif_observed_mean, 2)
    ),
    low_climsen_signi = ifelse(
      dif_low_signi == F, paste(round(dif_low_mean, 2), "*"), round(dif_low_mean, 2)
    ),
    high_climsen_signi = ifelse(
      dif_high_signi == F, paste(round(dif_high_mean, 2), "*"), round(dif_high_mean, 2)
    )
  ) |> 
  select(
    species.cor,
    observed_climsen_signi,
    low_climsen_signi,
    high_climsen_signi
  )

sp_importance_signi_count <- sp_importance_signi |> 
  mutate_at(
    vars(observed_climsen_signi, low_climsen_signi, 
         high_climsen_signi),
    list(
     count = \(x) str_detect(x, "\\*")
    )
  )

names(sp_importance_signi_count)

sp_importance_per <- tibble(
  observed_per = sum(sp_importance_signi_count$observed_climsen_signi_count == T) / nrow(sp_importance_signi) * 100,
  low_per = sum(sp_importance_signi_count$low_climsen_signi_count == T) / nrow(sp_importance_signi) * 100,
  high_per = sum(sp_importance_signi_count$high_climsen_signi_count == T) / nrow(sp_importance_signi) * 100
)

names(sp_importance_signi)

sp_importance_per_tb <- tibble(
  species.cor = "Percentage",
  observed_climsen_signi = round(sp_importance_per$observed_per, 1), 
  low_climsen_signi = round(sp_importance_per$low_per, 1),
  high_climsen_signi = round(sp_importance_per$high_per, 1)
)

sp_mean_tb <- tibble(
  species.cor = "Mean",
  observed_climsen_signi = round(mean(predictions_imp$dif_observed_mean), 2), 
  low_climsen_signi = round(mean(predictions_imp$dif_low_mean), 2),
  high_climsen_signi = round(mean(predictions_imp$dif_high_mean), 2)
)

sp_importance_signi_per <- rbind(sp_importance_signi, sp_mean_tb, sp_importance_per_tb)

names(sp_importance_signi_per)

# initial number of stems
sp_mean_n0 <- predictions_all_changes |> 
  group_by(species.cor) |> 
  summarise(
    n.plot0.mean = round(mean(n.plot0 / plot.area))
  )

# equal weight for each species
mean_n0 <- round(mean(sp_mean_n0$n.plot0.mean))
sd_n0 <- round(sd(sp_mean_n0$n.plot0.mean))

mean_n0_tb <- tibble(
  species.cor = "Mean",
  n.plot0.mean = round(mean_n0)
)

all_mean_n0 <- rbind(sp_mean_n0, mean_n0_tb)

sp_importance_signi_per_n0 <- left_join(sp_importance_signi_per, all_mean_n0, by = "species.cor")

table_S3 <- sp_importance_signi_per_n0 |> 
  mutate(species.cor2 = species.cor) |> 
  select(species.cor, observed_climsen_signi, low_climsen_signi, high_climsen_signi, n.plot0.mean) |> 
  gt(
    groupname_col = "species.cor2"
  ) |>
  cols_label(
    species.cor = "Species",
    observed_climsen_signi = "Climatic sensitivity (actual)",
    low_climsen_signi = "Climatic sensitivity (early)",
    high_climsen_signi = "Climatic sensitivity (late)", 
    n.plot0.mean = "Initial number of stems"
    ) |> 
  tab_style(
    style = list(
      cell_text(weight = "bold")
    ),
    locations = list(
      cells_column_labels(gt::everything())
    )
    )  |>
  cols_align(
    align = "center",
    columns = gt::everything()
    ) |> 
  sub_missing(
    columns = gt::everything(),
    missing_text = "-"
    ) |> 
  tab_style(
    style = cell_text(style = "italic"),
    locations = cells_body(
      columns = c(species.cor)
    )
  )

table_S3

gtsave(table_S3, "table_S4.1.rtf",
       path = here("03_results", "tables"))

# only for significant changes
# positive (towards cold & wet)
# actual
sum(sp_importance_signi_count$observed_climsen_signi_count == T & sp_importance_signi_count$observed_climsen_signi > 0) / nrow(sp_importance_signi_count) * 100

# early
sum(sp_importance_signi_count$low_climsen_signi_count == T & sp_importance_signi_count$low_climsen_signi > 0) / nrow(sp_importance_signi_count) * 100

# late
sum(sp_importance_signi_count$high_climsen_signi_count == T & sp_importance_signi_count$high_climsen_signi > 0) / nrow(sp_importance_signi_count) * 100

# negative (towards warm & arid)
# actual
sum(sp_importance_signi_count$observed_climsen_signi_count == T & sp_importance_signi_count$observed_climsen_signi < 0) / nrow(sp_importance_signi_count) * 100

# early
sum(sp_importance_signi_count$low_climsen_signi_count == T & sp_importance_signi_count$low_climsen_signi < 0) / nrow(sp_importance_signi_count) * 100

# late
sum(sp_importance_signi_count$high_climsen_signi_count == T & sp_importance_signi_count$high_climsen_signi < 0) / nrow(sp_importance_signi_count) * 100

n_species_signi_text <- tibble(
  for_dev = c(
    "Actual stand development",
    "Early stand development",
    "Late stand development"
  ),
  Increase = c(
    sum(sp_importance_signi_count$observed_climsen_signi_count == T & sp_importance_signi_count$observed_climsen_signi > 0),
    sum(sp_importance_signi_count$low_climsen_signi_count == T & sp_importance_signi_count$low_climsen_signi > 0),
    sum(sp_importance_signi_count$high_climsen_signi_count == T & sp_importance_signi_count$high_climsen_signi > 0)
    ),
  Decrease = c(
    sum(sp_importance_signi_count$observed_climsen_signi_count == T & sp_importance_signi_count$observed_climsen_signi < 0),
    sum(sp_importance_signi_count$low_climsen_signi_count == T & sp_importance_signi_count$low_climsen_signi < 0),
    sum(sp_importance_signi_count$high_climsen_signi_count == T & sp_importance_signi_count$high_climsen_signi < 0)
  )
)

# n. species significant in early and late
# towards cold & wet
n_species_signi_low_high_cw <- sp_importance_signi_count |> 
  filter(
    (low_climsen_signi_count == T & 
       low_climsen_signi > 0) &
      (high_climsen_signi_count == T & 
         high_climsen_signi > 0)
  )

round(nrow(n_species_signi_low_high_cw) / nrow(sp_importance_signi_count) * 100, 1)

# towards warm & arid
n_species_signi_low_high_wa <- sp_importance_signi_count |> 
  filter(
    (low_climsen_signi_count == T & 
       low_climsen_signi < 0) &
      (high_climsen_signi_count == T & 
         high_climsen_signi < 0)
  )

round(nrow(n_species_signi_low_high_wa) / nrow(sp_importance_signi_count) * 100, 1)

```

```{r fig3_main}

# species
pred_changes_l_rel_sp <- pred_changes_l_rel |> 
  filter(
    species.cor == "Acer rubrum" |
    species.cor == "Abies concolor" |
    species.cor == "Pinus ponderosa" |
    species.cor == "Populus tremuloides" |
    species.cor == "Pinus echinata" |
    species.cor == "Pinus sylvestris" |
    species.cor == "Picea abies" |
    species.cor == "Fagus sylvatica" |
    species.cor == "Quercus robur" |
    species.cor == "Quercus ilex"
    )

predictions_imp_l <- predictions_imp |>
  pivot_longer(
    cols = c(
      dif_observed_mean,
      dif_low_mean,
      dif_high_mean
      ),
    names_to = "name_diff_fd",
    values_to = "val_diff_fd"
    ) |> 
  group_by(name_diff_fd) |> 
  mutate(
    dif_mean_all = mean(val_diff_fd, na.rm = T)
  )

mean(predictions_imp$dif_observed_mean)
mean(predictions_imp$dif_low_mean)
mean(predictions_imp$dif_high_mean)

predictions_imp_l_rel <- predictions_imp_l |>
  mutate(
    name_diff_fd = case_when(
      name_diff_fd == "dif_observed_mean" ~ "Actual stand development",
      name_diff_fd == "dif_low_mean" ~ "Early stand development",
      T ~ "Late stand development"
    ),
    name_diff_fd = as.factor(name_diff_fd),
    name_diff_fd = fct_relevel(
    name_diff_fd,
    "Actual stand development",
    "Early stand development",
    "Late stand development"
    )
  )

levels(predictions_imp_l_rel$name_diff_fd)

df_text_mean <- predictions_imp_l_rel |> 
  group_by(name_diff_fd) |> 
  summarise(
    predFE_mean_all = round(mean(val_diff_fd, na.rm = T), 1),
    predFE_sd_all = round(sd(val_diff_fd, na.rm = T), 1),
    predFE_se_all = round(sd(val_diff_fd, na.rm = T) / sqrt(length(unique(species.cor))), 1)
  ) |> 
  mutate(
    x = 7.5,
    y = 12
  )

test_that("SE is OK", {
  expect_equal(
    round(sd(predictions_imp_l_rel$val_diff_fd[predictions_imp_l_rel$name_diff_fd == "Early stand development"]) / sqrt(73), 1),
    df_text_mean$predFE_se_all[df_text_mean$name_diff_fd == "Early stand development"]
  )
})

df_text_mean_sp <- left_join(df_text_mean, n_species_signi_text, by = c("name_diff_fd" = "for_dev"))

gg_sensitivity_hist <- function(df, text_mean) {
 ggplot(df, 
         aes(x = val_diff_fd, fill = after_stat(x))) +
    geom_histogram(
      boundary = 0,
      binwidth = .75, colour = "black", linewidth = .25
    ) +
    geom_vline(aes(xintercept = 0),
               linetype = "dashed",
               colour = "black", linewidth = .75) +
    facet_wrap(name_diff_fd ~ .) +
    labs(y = "N. species", x = "") +
    scale_fill_gradient2(
      mid = "white",
      midpoint = 0,
      low = scales::muted("#B2182B"),
      high = scales::muted("#2166AC"),
      name = expression(atop("Climatic sensitivity (Cold & wet - Warm & arid)", "Mean annual change n. stems per hectare"))
    ) +
    theme(
      legend.position = "bottom",
      strip.background = element_blank(),
      strip.text =  element_blank(),
      plot.margin = margin(0, 0, 0, 0),
      axis.title = element_text(colour = "black", size = 10),
      axis.text = element_text(size = 10, colour = "black"),
      legend.text = element_text(size = 10),
      legend.title = element_text(size = 10),
      panel.grid.major = element_line(colour = "grey90", linewidth = 0.5),
      axis.line = element_blank(),
      legend.key = element_blank(),
      panel.background = element_blank(),
      panel.spacing = unit(0, "lines")
    ) +
    geom_text(data = text_mean,
              aes(label = paste(predFE_mean_all, "\ub1", predFE_se_all),
                  x = x, y = y),
              size = 3.5,
              color = "grey40") +
    geom_text(data = text_mean, 
              aes(label = paste(Increase, "    ", "\n\n"),
                  x = x, y = y), 
              size = 3.5, color = "#2166AC") +
    geom_text(data = text_mean, 
              aes(label = "/\n\n",
                  x = x, y = y),
              size = 3.5) +
    geom_text(data = text_mean,
              aes(label = paste("     ", Decrease, "\n\n"),
                  x = x, y = y),
              size = 3.5, color = "#B2182B")
}

fig3_hist <- gg_sensitivity_hist(
  df = predictions_imp_l_rel,
  text_mean = df_text_mean_sp
) +
  theme(
    legend.margin = margin(0, 0, 0, 0),
    legend.box.margin = margin(-10, -10, 0, -10),
    panel.spacing = unit(.7, "lines")
  ) +
  labs(tag = "(B)")

ggsave(
  plot = fig3_hist,
  here("03_results", "figures", "fig3", "fig3_hist.png"),
  width = 8, height = 2.1,
  dpi = 600
)

fig3_slab <- (gg_slab_sp_clim(dat = pred_changes_l_rel_sp) +
                theme(plot.margin = margin(0, 2, 0, 0, "cm"),
                      legend.text = element_text(color = "black", size = 10),
                      strip.text = element_text(color = "black", size = 10),
                      axis.title.x = element_text(color = "black", size = 10),
                      axis.text.x = element_text(color = "black", size = 10),
                      axis.text.y = element_text(color = "black", size = 10,
                                                 face = "italic")) + labs(tag = "(A)")) /
  plot_spacer() +
  plot_layout(heights = c(4, 2))

ggsave(
  plot = fig3_slab,
  here("03_results", "figures", "fig3", "fig3_slab.png"),
  width = 10, height = 8.2,
  dpi = 600
)

fig3_hist_m <- image_read(here("03_results", "figures", "fig3", "fig3_hist.png"))

fig3_slab_m <- image_read(here("03_results", "figures", "fig3", "fig3_slab.png"))

fig3_main_m <- image_composite(
  fig3_slab_m, fig3_hist_m,
  offset = "+1050+3650"
  )

fig3_main_m

image_write(fig3_main_m, here(
  "03_results", "figures", "fig3", "fig3_main.tiff"
), density = 1200)

image_write(fig3_main_m, here(
  "03_results", "figures", "fig3", "fig3_main.png"
), density = 1200)

```
