---
title: "Quantify the effect of species minimum temperature and aridity on species climatic sensitivity"
output: github_document
editor_options: 
  chunk_output_type: console
---

PROBAR CON LOGS

```{=html}
<style type="text/css">
pre {
  font-size: 10px
}
</style>
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = T, message = F, warning = F)

library(tidyverse)
library(lme4)
library(here)
library(testthat)
library(fs)
library(DHARMa)
library(patchwork)
# https://strengejacke.github.io/ggeffects/articles/introduction_randomeffects.html
library(ggeffects)

```

```{r read}

read_data <- function(data_dir){
  fs::dir_ls(data_dir, regexp = "\\.rds$") |>
    purrr::map(read_rds)
}

all_files <- read_data(data_dir = here("01_data", "species_predictions"))

all_files_dir <- dir_ls(here("01_data", "species_predictions"), regexp = "\\.rds$")

all_files_dir_names <- map(all_files_dir, ~str_extract(.x, "[^/]*$")) |> 
  map(~str_replace(.x, "_", " ")) |> 
  map(~str_extract(.x,  "[^_]+")) |>
  unname()

names(all_files) <- all_files_dir_names

```

```{r intersp}

mutate_name <- function(x, names_sp){
  all_files[[x]] |> 
    dplyr::mutate(
      species.cor = names_sp
    )
}

arg2_x_names_sp <- list(x = seq_along(all_files), names_sp = names(all_files))

all_files_tb <- arg2_x_names_sp |> 
  pmap_df(mutate_name)

predictions_all_changes <- all_files_tb

names(predictions_all_changes)

predictions_species_climsen <- predictions_all_changes |>
  mutate(
    high.climsen = ((predFE_high_cold_wet - n.plot0) / census.interval / plot.area) - ((predFE_high_warm_arid - n.plot0) / census.interval / plot.area)
  )

```

```{r remove_chunk}

data_model <- readRDS(file = here("01_data", "data_model.rds"))

data_model_traits <- data_model |> 
  distinct(species.cor, 
           mean.wood.density,
           mean.seed.dry.mass)

predictions_species_climsen <- predictions_species_climsen |>
  select(!c(mean.wood.density, mean.seed.dry.mass))

predictions_species_climsen <- left_join(
  predictions_species_climsen, 
  data_model_traits, by = "species.cor"
)

```

```{r lm_model}

# response variable distributions
hist(predictions_species_climsen$high.climsen, breaks = 100)
summary(predictions_species_climsen$high.climsen)

names(predictions_species_climsen)

summary(predictions_species_climsen$bio11.mean)
summary(predictions_species_climsen$aridity.mean)
summary(predictions_species_climsen$mean.wood.density)
summary(predictions_species_climsen$mean.seed.dry.mass)

# a lm calculating the mean change per species
predictions_group <- predictions_species_climsen |> 
  group_by(species.cor) |> 
  summarise(
    high.climsen.sp = mean(high.climsen, na.rm = T),
    bio11.mean.sp = mean(bio11.mean, na.rm = T),
    aridity.mean.sp = mean(aridity.mean, na.rm = T),
    mean.wood.density.sp = mean(mean.wood.density, na.rm = T),
    mean.seed.dry.mass.sp = mean(mean.seed.dry.mass, na.rm = T)
  )

# standardisation
predictions_group_std <- predictions_group |>
  mutate(
    across(c(bio11.mean.sp, aridity.mean.sp,
             mean.wood.density.sp, mean.seed.dry.mass.sp),
           \(x) as.numeric(scale(x, center = TRUE, scale = TRUE)), .names = "{.col}.std")
  )

summary(predictions_group_std$bio11.mean.sp.std)
summary(predictions_group_std$aridity.mean.sp.std)
summary(predictions_group_std$mean.wood.density.sp.std)
summary(predictions_group_std$mean.seed.dry.mass.sp.std)
summary(predictions_group_std$high.climsen.sp)

mod_lm <- lm(
  high.climsen.sp ~ bio11.mean.sp.std + 
    aridity.mean.sp.std +
    mean.wood.density.sp.std +
    mean.seed.dry.mass.sp.std,
  data = as.data.frame(predictions_group_std)
)

summary(mod_lm)

simres <- simulateResiduals(mod_lm)
x11()
par(mfrow = c(2, 2))
plot(simres)

```

```{r fig3_main}

predict_tmin <- ggpredict(
  model = mod_lm, 
  terms = "bio11.mean.sp.std",
  type = "fixed",
  ci.lvl = 0.68
)

predict_aridity <- ggpredict(
  model = mod_lm, 
  terms = "aridity.mean.sp.std [-2.5:6.5]",
  type = "fixed",
  ci.lvl = 0.68
)

predict_wd <- ggpredict(
  model = mod_lm, 
  terms = "mean.wood.density.sp.std",
  type = "fixed",
  ci.lvl = 0.68
)

predict_sdm <- ggpredict(
  model = mod_lm, 
  terms = "mean.seed.dry.mass.sp.std [-1:5]",
  type = "fixed",
  ci.lvl = 0.68
)

plot_ggeffects_lm <- function(pred, xlab){
  plot(
    pred, add.data = T,
    alpha = .15
    ) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "grey20") +
    labs(
      y = expression(atop("Climatic sensitivity (Cold & wet - Warm & arid)", "Annual change n. stems per hectare")),
      x = xlab,
      ) +
    coord_cartesian(
      ylim = c(-2.5, 2.5),
      ) +
    theme(
      panel.grid.major = element_line(colour = "grey90", linewidth = 0.5),
      panel.background = element_blank(),
      axis.text = element_text(size = 10, colour = "black"),
      axis.title = element_text(size = 10, colour = "black"),
      legend.position = "none"
    ) +
  ggtitle("")
}

# reverse transformation
# https://ourcodingclub.github.io/tutorials/data-scaling/
scaled_rev_bio11_lm <- predict_tmin[["x"]] * sd(predictions_group_std$bio11.mean.sp) +
  mean(predictions_group_std$bio11.mean.sp)

scaled_rev_aridity_lm <- predict_aridity[["x"]] * sd(predictions_group_std$aridity.mean.sp) +
  mean(predictions_group_std$aridity.mean.sp)

scaled_rev_wd_lm <- predict_wd[["x"]] * sd(predictions_group_std$mean.wood.density.sp) +
  mean(predictions_group_std$mean.wood.density.sp)

scaled_rev_sdm_lm <- predict_sdm[["x"]] * sd(predictions_group_std$mean.seed.dry.mass.sp) +
  mean(predictions_group_std$mean.seed.dry.mass.sp)

plot_tmin <- plot_ggeffects_lm(predict_tmin, "Minimum temperature niche position")

plot_aridity <- plot_ggeffects_lm(predict_aridity, "Aridity niche position")

plot_wd <- plot_ggeffects_lm(predict_wd, "Wood density")

plot_sdm <- plot_ggeffects_lm(predict_sdm, "Seed dry mass")

all_plot_ggeffects_lm <- plot_tmin + 
  scale_x_continuous(
    breaks = plot_tmin$data$x[c(1, 3, 5, 7, 9, 11)],
    labels = round(scaled_rev_bio11_lm[c(1, 3, 5, 7, 9, 11)], 1)
  ) +
  plot_aridity + 
  scale_x_continuous(
    breaks = plot_aridity$data$x[c(1, 3, 5, 7, 9)],
    labels = round(scaled_rev_aridity_lm[c(1, 3, 5, 7, 9)], 1)
  ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  plot_wd + 
  scale_x_continuous(
    breaks = plot_wd$data$x[c(1, 5, 9, 13)],
    labels = round(scaled_rev_wd_lm[c(1, 5, 9, 13)], 1)
  ) +
  plot_sdm + 
  scale_x_continuous(
    breaks = plot_sdm$data$x[c(1, 3, 5, 7)],
    labels = round(scaled_rev_sdm_lm[c(1, 3, 5, 7)], 1)
  ) +
  theme(
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  plot_annotation(tag_levels = "A", tag_prefix = "(", tag_suffix = ")") +
  plot_layout(ncol = 2)

all_plot_ggeffects_lm

ggsave(
  plot = all_plot_ggeffects_lm,
  here("03_results", "figures", "fig3", "fig3_main.png"),
  width = 9, height = 8,
  dpi = 600
)

```

```{r lmer_model}

# lm robustness diagnostic

predictions_climsen_std <- predictions_species_climsen |>
    dplyr::select(
    species.cor, tmt.plot.id, 
    census.interval, plot.area,
    high.climsen,
    bio11.mean, aridity.mean,
    mean.wood.density, mean.seed.dry.mass
  ) |> 
  mutate(
    across(c(bio11.mean, aridity.mean,
             mean.wood.density, mean.seed.dry.mass),
           \(x) as.numeric(scale(x, center = TRUE, scale = TRUE)), .names = "{.col}.std")
  )

mod_lmer <- lmer(
  high.climsen ~ (1|tmt.plot.id) +
    (1|species.cor) +
    bio11.mean.std + aridity.mean.std + 
    mean.wood.density.std + mean.seed.dry.mass.std,
  data = as.data.frame(predictions_climsen_std)
)

summary(mod_lmer)

predict_ggeffects_lmer <- function(m, var){
  ggpredict(model = m, 
            terms = var,
            type = "fixed",
            ci.lvl = 0.68)
}

var_v_lmer <- c(
  "bio11.mean.std", 
  "aridity.mean.std",
  "mean.wood.density.std",
  "mean.seed.dry.mass.std"
)

predictions_lmer <- map(var_v_lmer, \(x) predict_ggeffects_lmer(m = mod_lmer, var = x))

plot_ggeffects_lmer <- function(pred, xlab){
  plot(
    pred, add.data = T, dot.size = .1,
    alpha = .15, dot.alpha = .03
    ) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "grey20") +
    labs(
      y = expression(atop("Climatic sensitivity (Cold & wet - Warm & arid)", "Annual change n. stems per hectare")),
      x = xlab,
      ) +
    coord_cartesian(
      ylim = c(-2.5, 2.5),
      ) +
    theme(
      panel.grid.major = element_line(colour = "grey90", linewidth = 0.5),
      panel.background = element_blank(),
      axis.text = element_text(size = 10, colour = "black"),
      axis.title = element_text(size = 10, colour = "black"),
      legend.position = "none"
    ) +
  ggtitle("")
}

xlab_v_lmer <- c(
  "Minimum temperature niche position",
  "Aridity niche position",
  "Wood density",
  "Seed dry mass"
)

arg2_pred_xlab_v_lmer <- list(
  pred = predictions_lmer,
  xlab = xlab_v_lmer
  )

all_plot_ggeffects_lmer <- arg2_pred_xlab_v_lmer |> 
  pmap(plot_ggeffects_lmer)

scaled_rev_bio11_lmer <- predictions_lmer[[1]][["x"]] * sd(predictions_climsen_std$bio11.mean) +
  mean(predictions_climsen_std$bio11.mean)

scaled_rev_aridity_lmer <- predictions_lmer[[2]][["x"]] * sd(predictions_climsen_std$aridity.mean) +
  mean(predictions_climsen_std$aridity.mean)

scaled_rev_wd_lmer <- predictions_lmer[[3]][["x"]] * sd(predictions_climsen_std$mean.wood.density) +
  mean(predictions_climsen_std$mean.wood.density)

scaled_rev_sdm_lmer <- predictions_lmer[[4]][["x"]] * sd(predictions_climsen_std$mean.seed.dry.mass) +
  mean(predictions_climsen_std$mean.seed.dry.mass)

all_plot_ggeffects_lmer <- all_plot_ggeffects_lmer[[1]] + 
  scale_x_continuous(
    breaks = all_plot_ggeffects_lmer[[1]]$data$x[c(1, 3, 5, 7, 9)],
    labels = round(scaled_rev_bio11_lmer[c(1, 3, 5, 7, 9)], 1)
    ) +
  all_plot_ggeffects_lmer[[2]] + 
  scale_x_continuous(
    breaks = all_plot_ggeffects_lmer[[2]]$data$x[c(1, 3, 5, 7, 9, 11)],
    labels = round(scaled_rev_aridity_lmer[c(1, 3, 5, 7, 9, 11)], 1)
    ) +
  all_plot_ggeffects_lmer[[3]] + 
  scale_x_continuous(
    breaks = all_plot_ggeffects_lmer[[3]]$data$x[c(1, 3, 5, 7, 9, 11, 13)],
    labels = round(scaled_rev_wd_lmer[c(1, 3, 5, 7, 9, 11, 13)], 1)
    ) +
  all_plot_ggeffects_lmer[[4]] + 
  scale_x_continuous(
    breaks = all_plot_ggeffects_lmer[[4]]$data$x[c(1, 3, 5, 7, 9, 11, 13)],
    labels = round(scaled_rev_sdm_lmer[c(1, 3, 5, 7, 9, 11, 13)], 1)
    ) +
  plot_annotation(tag_levels = "A", tag_prefix = "(", tag_suffix = ")") +
  plot_layout(ncol = 2)

all_plot_ggeffects_lmer
  
ggsave(
  plot = all_plot_ggeffects_lmer,
  here("03_results", "figures", "fig3", "fig3_lmer.png"),
  width = 9, height = 8,
  dpi = 600
)

```

