---
title: "Carya alba"
output: github_document
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
pre {
font-size: 10px
}
</style>

```{r setup, include = F}
knitr::opts_chunk$set(eval = T, echo = TRUE, message = F, warning = F, out.width = "100%")

library(here)
library(tidyverse)
library(DHARMa)
library(patchwork)
library(gratia)
library(mgcv)
library(performance)
library(ggdist)
library(visreg)

source(here("02_analyses", "f_EDA.R"))

```

```{r read}

data_model <- readRDS(file = here("01_data", "data_model.rds"))

data_model <- data_model |> 
  mutate(
    l.n.plot0 = log(n.plot0),
    l.plot.area = log(plot.area),
    country = as.factor(country)
  )

class(data_model$country)

sp <- data_model |> 
  filter(species.cor == "Carya alba")

```

# EDA

## Univariate plots

```{r univariate}

plot_eda(sp)

# response variable distribution (after rpois)
ggplot(sp, aes(n.plot)) +
  geom_histogram(binwidth = 1) +
  coord_cartesian(xlim = c(0, max(sp$n.plot)))

```

## Data summary for all species together

```{r summary-all}

summary(data_model$n.plot)
summary(data_model$n.plot0)
summary(log(data_model$n.plot0))
summary(data_model$census.interval)
summary(data_model$for.dev)
summary(data_model$bio11)
summary(data_model$aridity)
summary(log(data_model$plot.area))

```

## Data summary for Carya alba

```{r summary-sp}

summary(sp$n.plot)
summary(sp$n.plot0)
summary(log(sp$n.plot0))
summary(sp$census.interval)
summary(sp$for.dev)
summary(sp$bio11)
summary(sp$aridity)
summary(log(sp$plot.area))

```

## Coplots

```{r coplot}

x11()
coplot_n0_ci(sp)
coplot_n0_fd(sp)
coplot_n0_fd_arid(sp)
coplot_n0_fd_bio11(sp)
coplot_fd_arid(sp)
coplot_fd_bio11(sp)

```

## Climate data covariation

```{r covariation}

ggplot(sp, aes(x = bio11, 
               y = aridity)) +
  geom_hex() +
  geom_smooth(method = "lm", col = "blue") +
  geom_smooth(col = "red")

cor(sp$bio11, sp$aridity)

```

# GAM fitting & diagnostics

```{r gam, warning = T, message = T}

if(length(unique(sp$country)) > 1){
  m <- gam(n.plot ~ l.n.plot0 * census.interval + 
             country +
             offset(l.plot.area) +
             te(bio11, aridity, for.dev, bs = "cr"),
           family = "nb",
           data = sp,
           method = "REML")
}else{
  m <- gam(n.plot ~ l.n.plot0 * census.interval + 
             offset(l.plot.area) +
             te(bio11, aridity, for.dev, bs = "cr"),
           family = "nb",
           data = sp,
           method = "REML")
}

summary(m)

x11()
gam.check(m)

performance::r2(m)

## visreg
visreg(m)
visreg(m, xvar = "bio11", by = "for.dev", breaks = c(0.25, 0.65))
visreg(m, xvar = "aridity", by = "for.dev", breaks = c(0.25, 0.65))

## gratia
gratia::appraise(m)
draw(m)

## Calibration plot
pred <- predict(m, newdata = sp, type = "response")
ggplot(data.frame(obs = sp$n.plot0, pred = pred)) +
  geom_point(aes(pred, obs)) +
  geom_abline(intercept = 0, slope = 1) +
  geom_smooth(aes(pred, obs))


## DHARMa
res <- simulateResiduals(m, integerResponse = TRUE)
x11()
plot(res)
plot(res, form = sp$l.n.plot0)
plot(res, form = sp$for.dev)
plot(res, form = sp$aridity)
plot(res, form = sp$tmin)

```

## Predictions

```{r predict}

fd_observed <- sp

bio11_q <- quantile(sp$bio11, c(0.25, 0.5, 0.75))
aridity_q <- quantile(sp$aridity, c(0.25, 0.5, 0.75))

# observed
## cold & wet edge
fd_observed_cold_wet <- sp |> 
  mutate(
    bio11 = bio11_q[[1]],
    aridity = aridity_q[[3]]
  )

## warm & arid edge
fd_observed_warm_arid <- sp |> 
  mutate(
    bio11 = bio11_q[[3]],
    aridity = aridity_q[[1]]
  )

## core
fd_observed_core <- sp |> 
  mutate(
    bio11 = bio11_q[[2]],
    aridity = aridity_q[[2]]
  )

# early
## cold & wet edge
fd_low_cold_wet <- sp |> 
  mutate(
    for.dev = 0.25,
    bio11 = bio11_q[[1]],
    aridity = aridity_q[[3]]
  )

## warm & arid edge
fd_low_warm_arid <- sp |> 
  mutate(
    for.dev = 0.25,
    bio11 = bio11_q[[3]],
    aridity = aridity_q[[1]]
  )

## core
fd_low_core <- sp |> 
  mutate(
    for.dev = 0.25,
    bio11 = bio11_q[[2]],
    aridity = aridity_q[[2]]
  )

# late
## cold & wet edge
fd_high_cold_wet <- sp |> 
  mutate(
    for.dev = 0.65,
    bio11 = bio11_q[[1]],
    aridity = aridity_q[[3]]
  )

## warm & arid edge
fd_high_warm_arid <- sp |> 
  mutate(
    for.dev = 0.65,
    bio11 = bio11_q[[3]],
    aridity = aridity_q[[1]]
  )

## core
fd_high_core <- sp |> 
  mutate(
    for.dev = 0.65,
    bio11 = bio11_q[[2]],
    aridity = aridity_q[[2]]
  )

newdata_list <- list(
  fd_observed,
  fd_observed_cold_wet,
  fd_observed_warm_arid,
  fd_observed_core,
  fd_low_cold_wet,
  fd_low_warm_arid,
  fd_low_core,
  fd_high_cold_wet,
  fd_high_warm_arid,
  fd_high_core
)

# make the predictions for each dataset
predictions <- map(newdata_list, ~predict(
  object = m, newdata = ., se.fit = TRUE, type = "response"
))

arg2_dat_pred <- list(dat = newdata_list, pred = predictions)

# add predictions to the corresponding dataset
add_predictions <- function(dat, pred){
  dat |> 
    mutate(
      predFE = pred$fit
    )
}

newdata_list_predictions <- arg2_dat_pred %>%
  pmap(add_predictions)

names(newdata_list_predictions) <- c(
  "fd_observed",
  "fd_observed_cold_wet",
  "fd_observed_warm_arid",
  "fd_observed_core",
  "fd_low_cold_wet",
  "fd_low_warm_arid",
  "fd_low_core",
  "fd_high_cold_wet",
  "fd_high_warm_arid",
  "fd_high_core"
)

# select the variables of interest from each dataset
predictions_selected <- map(
  newdata_list_predictions,
  ~dplyr::select(.x, tmt.plot.id, 
                 census.interval,
                 for.dev, n.plot0, 
                 n.plot, predFE))

# add prediction name to each dataset
mutate_name <- function(x, names_df){
  predictions_selected[[x]] |> 
    dplyr::mutate(
      df = names_df
    )
}

arg2_x_names_df <- list(x = 1:length(predictions_selected), names_df = names(predictions_selected))

predictions_selected <- arg2_x_names_df %>%
  pmap_df(mutate_name)

clean_predictions <- function(dat, pred_name){
  predictions_selected |> 
    filter(df == dat) |> 
    dplyr::select(tmt.plot.id,
                  census.interval,
                  n.plot0, n.plot, predFE) |> 
    rename({{pred_name}} := predFE)
}

dat_v <- c(
  "fd_observed",
  "fd_observed_cold_wet",
  "fd_observed_warm_arid",
  "fd_observed_core",
  "fd_low_cold_wet",
  "fd_low_warm_arid",
  "fd_low_core",
  "fd_high_cold_wet",
  "fd_high_warm_arid",
  "fd_high_core"
)

pred_name_v <- c(
  "predFE_observed",
  "predFE_observed_cold_wet",
  "predFE_observed_warm_arid",
  "predFE_observed_core",
  "predFE_low_cold_wet",
  "predFE_low_warm_arid",
  "predFE_low_core",
  "predFE_high_cold_wet",
  "predFE_high_warm_arid",
  "predFE_high_core"
)

arg2_dat_pred_v <- list(
  dat = dat_v,
  pred_name = pred_name_v
)

predictions_selected_changes <- arg2_dat_pred_v %>%
  pmap(clean_predictions)

predictions_all_changes <- predictions_selected_changes |>
  reduce(left_join, by = c("tmt.plot.id",
                           "n.plot", "n.plot0",
                           "census.interval"))

pred_all_changes_l <- predictions_all_changes |>
  pivot_longer(
    cols = c(
      predFE_observed,
      predFE_observed_cold_wet,
      predFE_observed_warm_arid,
      predFE_observed_core,
      predFE_low_cold_wet,
      predFE_low_warm_arid,
      predFE_low_core,
      predFE_high_cold_wet,
      predFE_high_warm_arid,
      predFE_high_core
    ),
    names_to = "name_diff_fd",
    values_to = "val_diff_fd"
  )

pred_changes_l_rel <- pred_all_changes_l |>
  mutate(
    name_diff_fd = fct_relevel(
      name_diff_fd, 
      "predFE_observed_cold_wet",
      "predFE_observed_warm_arid",
      "predFE_observed_core",
      "predFE_low_cold_wet",
      "predFE_low_warm_arid",
      "predFE_low_core",
      "predFE_high_cold_wet",
      "predFE_high_warm_arid",
      "predFE_high_core"
    )
  )

ggplot(pred_changes_l_rel, aes
       (x = name_diff_fd, y = val_diff_fd,
         fill = name_diff_fd)) +
  stat_pointinterval(
    point_interval = mean_qi, .width = .5,
    position = position_dodge(width = .4), alpha = .9,
  ) +
  ylab("No stems") +
  geom_hline(yintercept = 0, linetype = "dashed") +
  coord_flip() +
  theme(
    plot.title = element_text(color = "black", size = 10),
    plot.subtitle = element_text(color = "black", size = 8),
    legend.position = "none",
    panel.grid.major = element_line(colour = "grey90", size = 0.5),
    panel.background = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_text(color = "black", size = 10),
    axis.text.x = element_text(color = "black", size = 10),
    axis.text.y = element_text(color = "black", size = 10),
    strip.text = element_text(color = "black", size = 10)
  )

# evaluate predictions on the observed data
predictions_filtered_test <- predictions_selected |>
  filter(df == "fd_observed") |>
  dplyr::select(tmt.plot.id, n.plot, predFE)

ggplot(predictions_filtered_test, aes(
  predFE, n.plot
)) +
  geom_point(alpha = 0.3) +
  geom_abline(slope = 1, intercept = 0, col = "red")

saveRDS(predictions_all_changes, file = here("01_data", "species_predictions", paste(sub(" ", "_", "Carya alba"), "predictions.rds", sep = "_")))

```
